# NemoriaQuest basic configuration
# Docstring placeholder for future settings.
config-version: '1.0'
core:
  multi_version: ["1.21.8", "1.21.9", "1.21.10"]
  locale: en_US
  debug: false
  debug-to-log: false
  scoreboard_enabled: true
logging:
  level: INFO
pools_process_task_ticks: 1200
progress_notify_loop_actionbar: true
progress_notify_loop_title: true
progress_notify_actionbar_loop_millis: 2500
progress_notify_title_loop_millis: 2500
